# Generated by Django 5.1.6 on 2025-02-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('isDone', models.BooleanField(default=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
