# Generated by Django 5.1.6 on 2025-02-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todoapp_isdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='desc',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
